<?php
/**
 * ClinicFlow Master Configuration File
 * Auto-generated by install.php installer
 */

return [
    'db_driver' => 'mysql',
    'db_host'   => 'localhost',
    'db_port'   => '3306',
    'db_name'   => 'clinicflow',
    'db_user'   => 'root',
    'db_pass'   => '',

    'admin_doctor' => [
        'name'      => 'Dr. Sarah Jenkins',
        'specialty' => 'Internal Medicine',
    ]
];
